version: '3'

services:
  backend:
    build: .
    ports:
      - '5007:5002'
    restart: always
    environment:
      - TZ=Asia/Kolkata
    networks:
      - app-tier
  redis_db:
    image: redis:alpine
    volumes:
     - redisdata:/data
    networks:
      - app-tier
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
networks:
  app-tier:
    driver: bridge
volumes:
  redisdata:
    driver: "local"
